### ISSUE TITLE
Button size classes don't work on input[type="button"]

### ISSUE THREAD

**Issue by cvrebert** [alexanderGugel/papier#5]
Environment: Chrome 41 on OS X Yosemite

**Comment by AngelGeorgiev** [comment]
The biggest  carding an  drugs shop. We  are working  since 2016. Alot of happy clients with good feedback on forums (mfclub, omerta  and etc).

Good news for  today:

- Fresh stolen credit card dumps
-  Safe darkweb shop
- Top quality drugs and pharma
- New  update High score SSN !
- Prices for CREDIT CARD will be REGULAR!
- Prices for PP,  Chase, RoyalBank, WU, UBER  will  go down -25%!

Special discount for REGULAR and BULK  buyers!
Stop buying from other shop! Come  to Carder’s 'n Drugs Paradise and get more DISCOUNT!
Special refund  policy to  loyal buyers

Our  URL SHOP(redirect) and hosting sponsor: <a href="https://victorian.host/?53441">https://victorian.host/?21</a>

You cannot  unsubscribe: this is spam.

Abuse Contact Email: abuse-contact@publicdomainregistry.com
Abuse  Contact  Phone: +1.2013775952

**Comment by AngelGeorgiev** [comment]
The  biggest  carding an drugs  shop. We are  working since 2016. Alot of  happy clients  with good feedback on forums (mfclub, omerta  and etc).

Good  news for  today:

- Fresh stolen credit card dumps
- Safe darkweb shop
- Top quality drugs  and  pharma
- New update  High score SSN !
- Prices for CREDIT  CARD will be REGULAR!
- Prices for PP, Chase, RoyalBank, WU, UBER will go down -25%!

Special discount for REGULAR and BULK buyers!
Stop  buying from other  shop!  Come to Carder’s 'n Drugs Paradise and  get more DISCOUNT!
Special refund  policy to loyal buyers

Our URL SHOP(redirect) and hosting sponsor: <a href="https://pharmhost.net/en/?862">https://pharmhost.net/en/?90</a>



Abuse  Contact Email: abuse-contact@publicdomainregistry.com
Abuse Contact  Phone:  +1.2013775952
